apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfbvk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pfbvk
  template:
    metadata:
      labels:
        app: pfbvk
    spec:
      containers:
      - image: okteto.dev/pfbvk:latest
        name: pfbvk
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "d7d1b2a5-0894-44db-9bb2-32f650e0e090"
        - name: Vless_Path
          value: "/wdxcmszmygrdx"
        - name: Vmess_UUID
          value: "d7d1b2a5-0894-44db-9bb2-32f650e0e090"
        - name: Vmess_Path
          value: "/dcbjkedxrzkhotx"
        - name: Share_Path
          value: "/v2link"
